<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>

    <PackageId>DotI2p</PackageId>
    <Version>0.6.1</Version>
    <Authors>Rob Kaandorp</Authors>
    <Description>A .NET library for communicating with an I2Pd router via the SAM v3.1 protocol.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/robkaandorp/doti2p</PackageProjectUrl>
    <RepositoryUrl>https://github.com/robkaandorp/doti2p</RepositoryUrl>
    <PackageTags>i2p;i2pd;sam;privacy;anonymity</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Multiformats.Base" Version="2.0.2" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.8" />
  </ItemGroup>

</Project>
